### ISSUE TITLE
I got this error when running inference.py, can you help me fix this?

### ISSUE THREAD

**Issue by ngoc85672912341998N** [gallilmaimon/DISSC#2]
RuntimeError: CUDA error: invalid device ordinal
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.

**Comment by gallilmaimon** [comment]
Hey,

I was unable to reproduce your issue, probably something device and installation specific. If you provide more information about your system and installation (OS, gpu, versions) and exact command you ran it might be easier to help.

I assume you are referring to ```sr\inference.py``` which is the speech resynthesis code, highly based on the official repository, so maybe you can look there for further guidance - https://github.com/facebookresearch/speech-resynthesis

This seems to be a gpu issue. Are you running on a device with a coda compatible GPU? Does PyTorch recognise the GPUs properly? This can be checked with something like:
```
import torch
print(torch.cuda.is_available())  # should be true
print(torch.cuda.device_count())  # should return one or higher
```

**Comment by Yoloex** [comment]
Hi @gallilmaimon,
The same issue was produced from my side.
I tried with different torch versions.
```
torch1.9+cu111
torch1.10+cu102
torch1.13+cu117
```
I'm using Python3.8 and CUDA is enabled.

**Comment by gallilmaimon** [comment]
This seems to be that the default value for the num_gpus argument in the config for sr for VCTK is 2, which means it won't work out of the box on single GPU machines. 

Try changing this line https://github.com/gallilmaimon/DISSC/blob/d4ceca7f91c4e6afc96618649745e902fc2de720/sr/configs/VCTK/hubert100_lut.json#L9 in file '''sr/configs/VCTK/hubert100_lut.json''' to 1. 

If this solves the issue as expected I will update the default config for single GPU and add a comment in the readme file. Let me know.

**Comment by Yoloex** [comment]
@gallilmaimon 
Unfortunately, this is not working. I tried with `num_gpus: 2`.

**Comment by gallilmaimon** [comment]
@Yoloex 
You need to change the line I linked to  **num_gpus: 1** because I assume you only have 1 gpu. Generally speaking the invalid ordinal of the gpu means you are trying to access a gpu which the server doesn't have. Namely if you try to access devices 0 and 1 because the code suggests there are two gpus but only one exists, then you will get the error.

If you tell me exactly what command you are running it will be easier to debug remotely :)

**Comment by Yoloex** [comment]
@gallilmaimon 
Sure, I tried to run `python sr/inference.py --input_code_file data/unseen/pred_hubert/p231_encoded.txt --data_path data/unseen/wav --output_dir dissc_p231 --checkpoint_file sr/checkpoints/vctk_hubert --unseen_speaker --id_to_spkr data/Syn_VCTK/hubert100/id_to_spkr.pkl --vc` on Win 10.
And I tried with `num_gpus: 1`.

**Comment by gallilmaimon** [comment]
@Yoloex @ngoc85672912341998N 
Hey, having another look I noticed that this warning when running the script always appears in the speech resynthesis code, because of this (hard coded) line:

https://github.com/gallilmaimon/DISSC/blob/d4ceca7f91c4e6afc96618649745e902fc2de720/sr/inference.py#L288

which aims to use as many as 8 gpus when they exist. This is **not** a bug or error on its own, but rather a warning which you can safely ignore. If the code actually crashes (e.g. stops running) with an error it should appear at the end of the stack trace and I can help with that if you provide the error (maybe in a new issue for clarity). As this is part of the original speech-resynthesis code I am reluctant to make changes there but you are welcome to do so.

I was able to run the code successfully (with the above warning but managing to generate the files as expected) on a single GPU linux server with torch=1.13 (installed by anaconda).

**Comment by Yoloex** [comment]
@gallilmaimon 
Thanks for your reply.
Here's the whole error message when running `python sr/inference.py --input_code_file data/unseen/pred_hubert/p231_encoded.txt --data_path data/unseen/wav --output_dir dissc_p231 --checkpoint_file sr/checkpoints/vctk_hubert --unseen_speaker --id_to_spkr data/Syn_VCTK/hubert100/id_to_spkr.pkl --vc`
```
Process SpawnPoolWorker-8:
Traceback (most recent call last):
  File "C:\Users\{user}\anaconda3\envs\dissc\lib\multiprocessing\process.py", line 315, in _bootstrap
    self.run()
  File "C:\Users\{user}\anaconda3\envs\dissc\lib\multiprocessing\process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\{user}\anaconda3\envs\dissc\lib\multiprocessing\pool.py", line 109, in worker
    initializer(*initargs)
  File "E:\models\voice_conversion\DISSC\sr\inference.py", line 114, in init_worker
    generator = CodeGenerator(h).to(idx)
  File "C:\Users\{user}\anaconda3\envs\dissc\lib\site-packages\torch\nn\modules\module.py", line 987, in to
    return self._apply(convert)
  File "C:\Users\{user}\anaconda3\envs\dissc\lib\site-packages\torch\nn\modules\module.py", line 639, in _apply
    module._apply(fn)
  File "C:\Users\{user}\anaconda3\envs\dissc\lib\site-packages\torch\nn\modules\module.py", line 662, in _apply
    param_applied = fn(param)
  File "C:\Users\{user}\anaconda3\envs\dissc\lib\site-packages\torch\nn\modules\module.py", line 985, in convert
    return t.to(device, dtype if t.is_floating_point() or t.is_complex() else None, non_blocking)
RuntimeError: CUDA error: invalid device ordinal
CUDA kernel errors might be asynchronously reported at some other API call,so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
multiprocessing.pool.RemoteTraceback:
"""
Traceback (most recent call last):
  File "C:\Users\{user}\anaconda3\envs\dissc\lib\multiprocessing\pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "C:\Users\{user}\anaconda3\envs\dissc\lib\site-packages\torch\autograd\grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "E:\models\voice_conversion\DISSC\sr\inference.py", line 177, in inference
    code, gt_audio, filename, _ = dataset[item_index]
  File "E:\models\voice_conversion\DISSC\sr\dataset.py", line 269, in __getitem__
    mel_loss = mel_spectrogram(audio, self.n_fft, self.num_mels,
  File "E:\models\voice_conversion\DISSC\sr\dataset.py", line 54, in mel_spectrogram
    mel = librosa_mel_fn(sampling_rate, n_fft, num_mels, fmin, fmax)
TypeError: mel() takes 0 positional arguments but 5 were given
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "sr/inference.py", line 363, in <module>
    main()
  File "sr/inference.py", line 354, in main
    for i, _ in enumerate(pool.imap(inference, idx), 1):
  File "C:\Users\{user}\anaconda3\envs\dissc\lib\multiprocessing\pool.py", line 868, in next
    raise value
TypeError: mel() takes 0 positional arguments but 5 were given
```

**Comment by Yoloex** [comment]
It's working now. Thanks.

**Comment by gallilmaimon** [comment]
That's great! Anything particular regarding librosa versions or something you changed that I should note in the requirements or readme? If not I think I will close the issue for now :)

**Comment by Yoloex** [comment]
Sure, it was librosa.
Should add `librosa==0.9.1` to the `requirements.txt`.

**Comment by gallilmaimon** [comment]
I see, yeah the librosa installation should come from the installation of textlesslib as described in https://github.com/gallilmaimon/DISSC/tree/main#environment

And they don't specify a version. I am using 0.9.2. I think if librosa didn't break backwards compatibility then this should work when installing by the instructions. I will close the issue for now. Thanks
